export const Countries = [
    { name: 'Afghanistan', a2code: 'AF', a3code: 'AFG' },
    { name: 'Åland Islands', a2code: 'AX', a3code: 'ALA' },
    { name: 'Albania', a2code: 'AL', a3code: 'ALB' },
    { name: 'Algeria', a2code: 'DZ', a3code: 'DZA' },
    { name: 'American Samoa', a2code: 'AS', a3code: 'ASM' },
    { name: 'Andorra', a2code: 'AD', a3code: 'AND' },
    { name: 'Angola', a2code: 'AO', a3code: 'AGO' },
    { name: 'Anguilla', a2code: 'AI', a3code: 'AIA' },
    { name: 'Antarctica', a2code: 'AQ', a3code: 'ATA' },
    { name: 'Antigua & Barbuda', a2code: 'AG', a3code: 'ATG' },
    { name: 'Argentina', a2code: 'AR', a3code: 'ARG' },
    { name: 'Armenia', a2code: 'AM', a3code: 'ARM' },
    { name: 'Aruba', a2code: 'AW', a3code: 'ABW' },
    { name: 'Australia', a2code: 'AU', a3code: 'AUS' },
    { name: 'Austria', a2code: 'AT', a3code: 'AUT' },
    { name: 'Azerbaijan', a2code: 'AZ', a3code: 'AZE' },
    { name: 'Bahamas', a2code: 'BS', a3code: 'BHS' },
    { name: 'Bahrain', a2code: 'BH', a3code: 'BHR' },
    { name: 'Bangladesh', a2code: 'BD', a3code: 'BGD' },
    { name: 'Barbados', a2code: 'BB', a3code: 'BRB' },
    { name: 'Belarus', a2code: 'BY', a3code: 'BLR' },
    { name: 'Belgium', a2code: 'BE', a3code: 'BEL' },
    { name: 'Belize', a2code: 'BZ', a3code: 'BLZ' },
    { name: 'Benin', a2code: 'BJ', a3code: 'BEN' },
    { name: 'Bermuda', a2code: 'BM', a3code: 'BMU' },
    { name: 'Bhutan', a2code: 'BT', a3code: 'BTN' },
    { name: 'Bolivia', a2code: 'BO', a3code: 'BOL' },
    { name: 'Bosnia & Herzegovina', a2code: 'BA', a3code: 'BIH' },
    { name: 'Botswana', a2code: 'BW', a3code: 'BWA' },
    { name: 'Bouvet Island', a2code: 'BV', a3code: 'BVT' },
    { name: 'Brazil', a2code: 'BR', a3code: 'BRA' },
    { name: 'British Indian Ocean Territory', a2code: 'IO', a3code: 'IOT' },
    { name: 'British Virgin Islands', a2code: 'VG', a3code: 'VGB' },
    { name: 'Brunei', a2code: 'BN', a3code: 'BRN' },
    { name: 'Bulgaria', a2code: 'BG', a3code: 'BGR' },
    { name: 'Burkina Faso', a2code: 'BF', a3code: 'BFA' },
    { name: 'Burundi', a2code: 'BI', a3code: 'BDI' },
    { name: 'Cambodia', a2code: 'KH', a3code: 'KHM' },
    { name: 'Cameroon', a2code: 'CM', a3code: 'CMR' },
    { name: 'Canada', a2code: 'CA', a3code: 'CAN' },
    { name: 'Cape Verde', a2code: 'CV', a3code: 'CPV' },
    { name: 'Caribbean Netherlands', a2code: 'BQ', a3code: 'BES' },
    { name: 'Cayman Islands', a2code: 'KY', a3code: 'CYM' },
    { name: 'Central African Republic', a2code: 'CF', a3code: 'CAF' },
    { name: 'Chad', a2code: 'TD', a3code: 'TCD' },
    { name: 'Chile', a2code: 'CL', a3code: 'CHL' },
    { name: 'China', a2code: 'CN', a3code: 'CHN' },
    { name: 'Christmas Island', a2code: 'CX', a3code: 'CXR' },
    { name: 'Cocos (Keeling) Islands', a2code: 'CC', a3code: 'CCK' },
    { name: 'Colombia', a2code: 'CO', a3code: 'COL' },
    { name: 'Comoros', a2code: 'KM', a3code: 'COM' },
    { name: 'Congo - Brazzaville', a2code: 'CD', a3code: 'COD' },
    { name: 'Congo - Kinshasa', a2code: 'CG', a3code: 'COG' },
    { name: 'Cook Islands', a2code: 'CK', a3code: 'COK' },
    { name: 'Costa Rica', a2code: 'CR', a3code: 'CRI' },
    { name: "Côte d'Ivoire", a2code: 'CI', a3code: 'CIV' },
    { name: 'Croatia', a2code: 'HR', a3code: 'HRV' },
    { name: 'Cuba', a2code: 'CU', a3code: 'CUB' },
    { name: 'Curaçao', a2code: 'CW', a3code: 'CUW' },
    { name: 'Cyprus', a2code: 'CY', a3code: 'CYP' },
    { name: 'Czech Republic', a2code: 'CZ', a3code: 'CZE' },
    { name: 'Denmark', a2code: 'DK', a3code: 'DNK' },
    { name: 'Djibouti', a2code: 'DJ', a3code: 'DJI' },
    { name: 'Dominica', a2code: 'DM', a3code: 'DMA' },
    { name: 'Dominican Republic', a2code: 'DO', a3code: 'DOM' },
    { name: 'Ecuador', a2code: 'EC', a3code: 'ECU' },
    { name: 'Egypt', a2code: 'EG', a3code: 'EGY' },
    { name: 'El Salvador', a2code: 'SV', a3code: 'SLV' },
    { name: 'Equatorial Guinea', a2code: 'GQ', a3code: 'GNQ' },
    { name: 'Eritrea', a2code: 'ER', a3code: 'ERI' },
    { name: 'Estonia', a2code: 'EE', a3code: 'EST' },
    { name: 'Eswatini', a2code: 'SZ', a3code: 'SWZ' },
    { name: 'Ethiopia', a2code: 'ET', a3code: 'ETH' },
    { name: 'Falkland Islands', a2code: 'FK', a3code: 'FLK' },
    { name: 'Faroe Islands', a2code: 'FO', a3code: 'FRO' },
    { name: 'Fiji', a2code: 'FJ', a3code: 'FJI' },
    { name: 'Finland', a2code: 'FI', a3code: 'FIN' },
    { name: 'France', a2code: 'FR', a3code: 'FRA' },
    { name: 'French Guiana', a2code: 'GF', a3code: 'GUF' },
    { name: 'French Polynesia', a2code: 'PF', a3code: 'PYF' },
    { name: 'French Southern Territories', a2code: 'TF', a3code: 'ATF' },
    { name: 'Gabon', a2code: 'GA', a3code: 'GAB' },
    { name: 'Gambia', a2code: 'GM', a3code: 'GMB' },
    { name: 'Georgia', a2code: 'GE', a3code: 'GEO' },
    { name: 'Germany', a2code: 'DE', a3code: 'DEU' },
    { name: 'Ghana', a2code: 'GH', a3code: 'GHA' },
    { name: 'Gibraltar', a2code: 'GI', a3code: 'GIB' },
    { name: 'Greece', a2code: 'GR', a3code: 'GRC' },
    { name: 'Greenland', a2code: 'GL', a3code: 'GRL' },
    { name: 'Grenada', a2code: 'GD', a3code: 'GRD' },
    { name: 'Guadeloupe', a2code: 'GP', a3code: 'GLP' },
    { name: 'Guam', a2code: 'GU', a3code: 'GUM' },
    { name: 'Guatemala', a2code: 'GT', a3code: 'GTM' },
    { name: 'Guernsey', a2code: 'GG', a3code: 'GGY' },
    { name: 'Guinea', a2code: 'GN', a3code: 'GIN' },
    { name: 'Guinea-Bissau', a2code: 'GW', a3code: 'GNB' },
    { name: 'Guyana', a2code: 'GY', a3code: 'GUY' },
    { name: 'Haiti', a2code: 'HT', a3code: 'HTI' },
    { name: 'Heard Island and McDonald Islands', a2code: 'HM', a3code: 'HMD' },
    { name: 'Honduras', a2code: 'HN', a3code: 'HND' },
    { name: 'Hong Kong', a2code: 'HK', a3code: 'HKG' },
    { name: 'Hungary', a2code: 'HU', a3code: 'HUN' },
    { name: 'Iceland', a2code: 'IS', a3code: 'ISL' },
    { name: 'India', a2code: 'IN', a3code: 'IND' },
    { name: 'Indonesia', a2code: 'ID', a3code: 'IDN' },
    { name: 'Iran', a2code: 'IR', a3code: 'IRN' },
    { name: 'Iraq', a2code: 'IQ', a3code: 'IRQ' },
    { name: 'Ireland', a2code: 'IE', a3code: 'IRL' },
    { name: 'Isle of Man', a2code: 'IM', a3code: 'IMN' },
    { name: 'Israel', a2code: 'IL', a3code: 'ISR' },
    { name: 'Italy', a2code: 'IT', a3code: 'ITA' },
    { name: 'Jamaica', a2code: 'JM', a3code: 'JAM' },
    { name: 'Japan', a2code: 'JP', a3code: 'JPN' },
    { name: 'Jersey', a2code: 'JE', a3code: 'JEY' },
    { name: 'Jordan', a2code: 'JO', a3code: 'JOR' },
    { name: 'Kazakhstan', a2code: 'KZ', a3code: 'KAZ' },
    { name: 'Kenya', a2code: 'KE', a3code: 'KEN' },
    { name: 'Kiribati', a2code: 'KI', a3code: 'KIR' },
    { name: 'Kuwait', a2code: 'KW', a3code: 'KWT' },
    { name: 'Kyrgyzstan', a2code: 'KG', a3code: 'KGZ' },
    { name: 'Laos', a2code: 'LA', a3code: 'LAO' },
    { name: 'Latvia', a2code: 'LV', a3code: 'LVA' },
    { name: 'Lebanon', a2code: 'LB', a3code: 'LBN' },
    { name: 'Lesotho', a2code: 'LS', a3code: 'LSO' },
    { name: 'Liberia', a2code: 'LR', a3code: 'LBR' },
    { name: 'Libya', a2code: 'LY', a3code: 'LBY' },
    { name: 'Liechtenstein', a2code: 'LI', a3code: 'LIE' },
    { name: 'Lithuania', a2code: 'LT', a3code: 'LTU' },
    { name: 'Luxembourg', a2code: 'LU', a3code: 'LUX' },
    { name: 'Macao', a2code: 'MO', a3code: 'MAC' },
    { name: 'Madagascar', a2code: 'MG', a3code: 'MDG' },
    { name: 'Malawi', a2code: 'MW', a3code: 'MWI' },
    { name: 'Malaysia', a2code: 'MY', a3code: 'MYS' },
    { name: 'Maldives', a2code: 'MV', a3code: 'MDV' },
    { name: 'Mali', a2code: 'ML', a3code: 'MLI' },
    { name: 'Malta', a2code: 'MT', a3code: 'MLT' },
    { name: 'Marshall Islands', a2code: 'MH', a3code: 'MHL' },
    { name: 'Martinique', a2code: 'MQ', a3code: 'MTQ' },
    { name: 'Mauritania', a2code: 'MR', a3code: 'MRT' },
    { name: 'Mauritius', a2code: 'MU', a3code: 'MUS' },
    { name: 'Mayotte', a2code: 'YT', a3code: 'MYT' },
    { name: 'Mexico', a2code: 'MX', a3code: 'MEX' },
    { name: 'Micronesia', a2code: 'FM', a3code: 'FSM' },
    { name: 'Moldova', a2code: 'MD', a3code: 'MDA' },
    { name: 'Monaco', a2code: 'MC', a3code: 'MCO' },
    { name: 'Mongolia', a2code: 'MN', a3code: 'MNG' },
    { name: 'Montenegro', a2code: 'ME', a3code: 'MNE' },
    { name: 'Montserrat', a2code: 'MS', a3code: 'MSR' },
    { name: 'Morocco', a2code: 'MA', a3code: 'MAR' },
    { name: 'Mozambique', a2code: 'MZ', a3code: 'MOZ' },
    { name: 'Myanmar (Burma)', a2code: 'MM', a3code: 'MMR' },
    { name: 'Namibia', a2code: 'NA', a3code: 'NAM' },
    { name: 'Nauru', a2code: 'NR', a3code: 'NRU' },
    { name: 'Nepal', a2code: 'NP', a3code: 'NPL' },
    { name: 'Netherlands', a2code: 'NL', a3code: 'NLD' },
    { name: 'New Caledonia', a2code: 'NC', a3code: 'NCL' },
    { name: 'New Zealand', a2code: 'NZ', a3code: 'NZL' },
    { name: 'Nicaragua', a2code: 'NI', a3code: 'NIC' },
    { name: 'Niger', a2code: 'NE', a3code: 'NER' },
    { name: 'Nigeria', a2code: 'NG', a3code: 'NGA' },
    { name: 'Niue', a2code: 'NU', a3code: 'NIU' },
    { name: 'Norfolk Island', a2code: 'NF', a3code: 'NFK' },
    { name: 'North Korea', a2code: 'KP', a3code: 'PRK' },
    { name: 'North Macedonia', a2code: 'MK', a3code: 'MKD' },
    { name: 'Northern Mariana Islands', a2code: 'MP', a3code: 'MNP' },
    { name: 'Norway', a2code: 'NO', a3code: 'NOR' },
    { name: 'Oman', a2code: 'OM', a3code: 'OMN' },
    { name: 'Pakistan', a2code: 'PK', a3code: 'PAK' },
    { name: 'Palau', a2code: 'PW', a3code: 'PLW' },
    { name: 'Palestine', a2code: 'PS', a3code: 'PSE' },
    { name: 'Panama', a2code: 'PA', a3code: 'PAN' },
    { name: 'Papua New Guinea', a2code: 'PG', a3code: 'PNG' },
    { name: 'Paraguay', a2code: 'PY', a3code: 'PRY' },
    { name: 'Peru', a2code: 'PE', a3code: 'PER' },
    { name: 'Philippines', a2code: 'PH', a3code: 'PHL' },
    { name: 'Pitcairn Islands', a2code: 'PN', a3code: 'PCN' },
    { name: 'Poland', a2code: 'PL', a3code: 'POL' },
    { name: 'Portugal', a2code: 'PT', a3code: 'PRT' },
    { name: 'Puerto Rico', a2code: 'PR', a3code: 'PRI' },
    { name: 'Qatar', a2code: 'QA', a3code: 'QAT' },
    { name: 'Réunion', a2code: 'RE', a3code: 'REU' },
    { name: 'Romania', a2code: 'RO', a3code: 'ROU' },
    { name: 'Russia', a2code: 'RU', a3code: 'RUS' },
    { name: 'Rwanda', a2code: 'RW', a3code: 'RWA' },
    { name: 'St. Barthélemy', a2code: 'BL', a3code: 'BLM' },
    { name: 'St. Helena', a2code: 'SH', a3code: 'SHN' },
    { name: 'St. Kitts & Nevis', a2code: 'KN', a3code: 'KNA' },
    { name: 'St. Lucia', a2code: 'LC', a3code: 'LCA' },
    { name: 'St. Martin', a2code: 'MF', a3code: 'MAF' },
    { name: 'St. Pierre and Miquelon', a2code: 'PM', a3code: 'SPM' },
    { name: 'St. Vincent & the Grenadines', a2code: 'VC', a3code: 'VCT' },
    { name: 'Samoa', a2code: 'WS', a3code: 'WSM' },
    { name: 'San Marino', a2code: 'SM', a3code: 'SMR' },
    { name: 'Sao Tome and Principe', a2code: 'ST', a3code: 'STP' },
    { name: 'Saudi Arabia', a2code: 'SA', a3code: 'SAU' },
    { name: 'Senegal', a2code: 'SN', a3code: 'SEN' },
    { name: 'Serbia', a2code: 'RS', a3code: 'SRB' },
    { name: 'Seychelles', a2code: 'SC', a3code: 'SYC' },
    { name: 'Sierra Leone', a2code: 'SL', a3code: 'SLE' },
    { name: 'Singapore', a2code: 'SG', a3code: 'SGP' },
    { name: 'Sint Maarten', a2code: 'SX', a3code: 'SXM' },
    { name: 'Slovakia', a2code: 'SK', a3code: 'SVK' },
    { name: 'Slovenia', a2code: 'SI', a3code: 'SVN' },
    { name: 'Solomon Islands', a2code: 'SB', a3code: 'SLB' },
    { name: 'Somalia', a2code: 'SO', a3code: 'SOM' },
    { name: 'South Africa', a2code: 'ZA', a3code: 'ZAF' },
    { name: 'South Georgia & the South Sandwich Islands', a2code: 'GS', a3code: 'SGS' },
    { name: 'South Korea', a2code: 'KR', a3code: 'KOR' },
    { name: 'South Sudan', a2code: 'SS', a3code: 'SSD' },
    { name: 'Spain', a2code: 'ES', a3code: 'ESP' },
    { name: 'Sri Lanka', a2code: 'LK', a3code: 'LKA' },
    { name: 'Sudan', a2code: 'SD', a3code: 'SDN' },
    { name: 'Suriname', a2code: 'SR', a3code: 'SUR' },
    { name: 'Svalbard & Jan Mayen', a2code: 'SJ', a3code: 'SJM' },
    { name: 'Sweden', a2code: 'SE', a3code: 'SWE' },
    { name: 'Switzerland', a2code: 'CH', a3code: 'CHE' },
    { name: 'Syria', a2code: 'SY', a3code: 'SYR' },
    { name: 'Taiwan', a2code: 'TW', a3code: 'TWN' },
    { name: 'Tajikistan', a2code: 'TJ', a3code: 'TJK' },
    { name: 'Tanzania', a2code: 'TZ', a3code: 'TZA' },
    { name: 'Thailand', a2code: 'TH', a3code: 'THA' },
    { name: 'Timor-Leste', a2code: 'TL', a3code: 'TLS' },
    { name: 'Togo', a2code: 'TG', a3code: 'TGO' },
    { name: 'Tokelau', a2code: 'TK', a3code: 'TKL' },
    { name: 'Tonga', a2code: 'TO', a3code: 'TON' },
    { name: 'Trinidad and Tobago', a2code: 'TT', a3code: 'TTO' },
    { name: 'Tunisia', a2code: 'TN', a3code: 'TUN' },
    { name: 'Turkey', a2code: 'TR', a3code: 'TUR' },
    { name: 'Turkmenistan', a2code: 'TM', a3code: 'TKM' },
    { name: 'Turks & Caicos Islands', a2code: 'TC', a3code: 'TCA' },
    { name: 'Tuvalu', a2code: 'TV', a3code: 'TUV' },
    { name: 'U.S. Virgin Islands', a2code: 'VI', a3code: 'VIR' },
    { name: 'Uganda', a2code: 'UG', a3code: 'UGA' },
    { name: 'Ukraine', a2code: 'UA', a3code: 'UKR' },
    { name: 'United Arab Emirates', a2code: 'AE', a3code: 'ARE' },
    { name: 'United Kingdom', a2code: 'GB', a3code: 'GBR' },
    { name: 'United States', a2code: 'US', a3code: 'USA' },
    { name: 'United States Minor Outlying Islands', a2code: 'UM', a3code: 'UMI' },
    { name: 'Uruguay', a2code: 'UY', a3code: 'URY' },
    { name: 'Uzbekistan', a2code: 'UZ', a3code: 'UZB' },
    { name: 'Vanuatu', a2code: 'VU', a3code: 'VUT' },
    { name: 'Vatican City', a2code: 'VA', a3code: 'VAT' },
    { name: 'Venezuela', a2code: 'VE', a3code: 'VEN' },
    { name: 'Vietnam', a2code: 'VN', a3code: 'VNM' },
    { name: 'Wallis & Futuna', a2code: 'WF', a3code: 'WLF' },
    { name: 'Western Sahara', a2code: 'EH', a3code: 'ESH' },
    { name: 'Yemen', a2code: 'YE', a3code: 'YEM' },
    { name: 'Zambia', a2code: 'ZM', a3code: 'ZMB' },
    { name: 'Zimbabwe', a2code: 'ZW', a3code: 'ZWE' },
];
